server:
  host: "127.0.0.1"
  port: 5555

client:
  host: "127.0.0.1"
  port: 5555

api_keys:
  openai: "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"
