llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "gpt-5-mini"  #  gpt-3.5-turbo or gpt-4-turbo
  base_url: ""  # or forward url / other llm url
  api_key: ""
models:
  gpt-5-mini:
    api_type: "openai"  # or azure / ollama / groq etc.
    model: "gpt-5-mini"  #  gpt-3.5-turbo or gpt-4-turbo
    base_url: ""  # or forward url / other llm url
    api_key: ""
CALC_USAGE: True 
